apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
  labels:
    app: hotstar-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotstar-clone  # Object with matchLabels
  template:
    metadata:
      labels:
        app: hotstar-clone
    spec:
      containers:
      - name: hotstar
        image: image-registry.openshift-image-registry.svc:50000/hotstar-devops/hotstar-clone:latest  # Use project name
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: REACT_APP_API_KEY  # Use secret
          valueFrom:
            secretKeyRef:
              name: hotstar-secrets
              key: tmdb-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always
      imagePullSecrets: []  # Add if using external registry like ECR
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%