apiVersion: v1
kind: Service
metadata:
  name: hotstar-service
  labels:
    app: hotstar-clone
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: hotstar-clone
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hotstar-route
  labels:
    app: hotstar-clone
spec:
  to:
    kind: Service
    name: hotstar-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None