apiVersion: v1
kind: Namespace
metadata:
  name: abdul-it
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: abdul-it
  labels:
      app: webapp
      type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx